spring:
    datasource:
        url: "jdbc:mysql://localhost:3306/my_database"
        username: root
        password: phidungx
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
